### ISSUE TITLE
Any info about using this module?

### ISSUE THREAD

**Issue by cool-dev-guy** [blueloveTH/ct-py#1]
Can you please provide any info about coding ct-py?

**Comment by blueloveTH** [comment]
I am making my own game via this module. I will update it when my game was done.

**Comment by blueloveTH** [comment]
You can check https://github.com/blueloveTH/pkpy-bindings to get a raylib bindings and code on raylib. Because ct-py is raylib bindings + an extra engine module.

**Comment by cool-dev-guy** [comment]
Thanks @blueloveTH ,now i understood how to code it.Also its very awesome that all the C++ functions are binded perfectly.Also I have a small doubt about the build path,because the path where main.py is absolute,so if i move the executable away to another directory or another system the code dosent execute.How to set the path to `relative` path?

Also you can close this issue. :)

**Comment by blueloveTH** [comment]
I haven't updated this repo for a while and sources are outdated. I recommend you to use raylib bindings directly instead of using this repo.

**Comment by blueloveTH** [comment]
If you are really interested about my lastest ct-py, you can leave an email here and I can send a copy of ct-py which is being used for my current game.

**Comment by cool-dev-guy** [comment]
@blueloveTH  thanks,here's my email cool.guy.cool.guy.dev@gmail.com

**Comment by blueloveTH** [comment]
Sent.



                       
Original
                       
                     

From:"cool-guy-dev"< ***@***.*** &gt;;

Date:2024/1/4 21:45

To:"blueloveTH/ct-py"< ***@***.*** &gt;;

CC:"BLUELOVETH"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [blueloveTH/ct-py] Any info about using this module? (Issue #1)




 
@blueloveTH  thanks,here's my email ***@***.***

**Comment by blueloveTH** [comment]
I am sorry your email provider rejected my zip archive, please download it at https://github.com/blueloveTH/ct-py/releases/tag/v0.0.1

**Comment by cool-dev-guy** [comment]
hey @blueloveTH ,But dosent it support linux,i somehow finished 100% build process but it gives me errors at last.
is there any way to make it work in linux?

**Comment by blueloveTH** [comment]
> hey @blueloveTH ,But dosent it support linux,i somehow(editted some files) finished 100% build process but it gives me errors at last. is there any way to make it work in linux?

Please wait for some days. I decide to rename this project into `carrotlib` and make it public. Documentations will be added soon.

**Comment by cool-dev-guy** [comment]
Hi i tried the build for windows and it works fine on linux too,thanks for helping me :)
